[project]
name = "pygammon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpython>=0.24",
    "pillow>=11.0.0",
    "pydantic-settings>=2.7.1",
    "pyside6>=6.8.0.2",
    "ruff>=0.7.3",
]
